#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.

from .build import MODEL_REGISTRY, build_model  # noqa
from .custom_video_model_builder import *  # noqa
from .handobj_kd_models import HandObjKdResNet
# from .handobj_models import HandObjResNet, HandObjMultiTaskSlowFastHSlow_2
from .handobj_models import *
from .handobj_multi_models import HandObjMultiTaskResNet, HandObjMultiTaskSlowFastHSlow
from .kd_models import KDResNet

from .handobj_multi_models_tpv import HandObjMultiTaskSlowFastHSlow_TPV
from .handobj_multi_models_tpv import HandObjMultiTaskSlowFastHSlow_TPV2

from .multi_models_lemma_tpv_3s_phrase_sf import MultiTaskSlowFast_LEMMA3S_PHRASE
from .multi_models_lemma_tpv_3s_2s_phrase_sf import MultiTaskSlowFast_LEMMA3S_2S_PHRASE

from .video_model_builder_char_lemma import SlowFast_LEMMA3S_PHRASE
from .video_model_builder_char_lemma_hoi import SlowFast_LEMMA3S_PHRASE_HOI
from .video_model_builder_char_lemma_hoi_2s import SlowFast_LEMMA3S_PHRASE_HOI_2S
from .video_model_builder_char_lemma_hoi_2s_cst import SlowFast_LEMMA3S_PHRASE_HOI_2S_CST
from .video_model_builder_char_lemma_hoi_2s_mm import SlowFast_LEMMA3S_PHRASE_HOI_2S_MM
from .video_model_builder_char_lemma_hoi_1s_s import ResNet_LEMMA3S_PHRASE_HOI_1S
from .video_model_builder_char_lemma_hoi_2s_s import ResNet_LEMMA3S_PHRASE_HOI_2S
from .video_model_builder_char_lemma_hoi_2s_sp import ResNet_LEMMA3S_PHRASE_HOI_2S_PROMPT
from .video_model_builder_char_lemma_hoi_2s_s_mm import ResNet_LEMMA3S_PHRASE_HOI_2S_MM
from .video_model_builder_char_lemma_hoi_2s_s_cst import ResNet_LEMMA3S_PHRASE_HOI_2S_CST
from .video_model_builder_char_lemma_hoi_2s_s_q import ResNet_LEMMA3S_PHRASE_HOI_2S_Q
from .video_model_builder_char_lemma_hoi_2s_s_m import ResNet_LEMMA3S_PHRASE_HOI_2S_M
from .video_model_builder_char_lemma_hoi_2s_s_vis import ResNet_VIS, ResNet_LEMMA3S_PHRASE_HOI_2S_VIS

from .multi_models_lemma_tpv_3s_2s_phrase_g2 import MultiResNet_LEMMA3S_PHRASE_HOI_2S
from .multi_models_lemma_tpv_3s_2s_phrase_g2_vis import *
from .multi_models_builder_ep_lemma_hoi_2s import SlowFast_LEMMA3S_PHRASE_EP_HOI_2S

from .transformer_char_lemma_2s import TimeSFormer_PHRASE_2S
from .transformer_lemma import TimeSFormer_LEMMA
from .video_transformer import SpaceTimeTransformer

from .multi_models import MultiTaskResNet
from .multi_models_k400 import MultiTaskResNet_K400
from .multi_models_k400_y import MultiTaskResNet_K400_Y
from .multi_models_k400_y_st import MultiTaskResNet_K400_YST
from .multi_models_k400_cos import MultiTaskResNet_K400_COS
from .multi_models_k400_cos_mt import MultiTaskResNet_K400_COS_MT
from .multi_models_k400_cos_fixmatch import MultiTaskResNet_K400_COS_FM
from .multi_models_k400_cos_fixmatch_2 import MultiTaskResNet_K400_COS_FM2
from .multi_models_k400_cos_fixmatch_k400 import MultiTaskResNet_K400_COS_FM_K400
from .multi_models_k400_cos_fixmatch_st import MultiTaskResNet_K400_COS_FM_ST
from .multi_models_k400_cos_fixmatch_st_2 import MultiTaskResNet_K400_COS_FM_ST2
from .multi_models_k400_cos_fixmatch_st_k400 import MultiTaskResNet_K400_COS_FM_ST_K400
from .multi_models_k400_cos_fixmatch_pa import MultiTaskResNet_K400_COS_FM_PA
from .multi_models_k400_cos_fixmatch_st_pa import MultiTaskResNet_K400_COS_FM_ST_PA
from .multi_models_lemma_tpv_2 import MultiTaskResNet_LEMMA2
from .multi_models_lemma_tpv_3 import MultiTaskResNet_LEMMA3
from .multi_models_lemma_tpv_3_div import MultiTaskResNet_LEMMA3_DIV
from .multi_models_lemma_tpv_3_moco import MultiTaskResNet_LEMMA3_MOCO
from .multi_models_lemma_tpv_3_moco_s import MultiTaskResNet_LEMMA3_MOCO_S
from .multi_models_lemma_tpv_3s import MultiTaskResNet_LEMMA3S
from .multi_models_lemma_tpv_3s_2s import MultiTaskResNet_LEMMA3S_2S
from .multi_models_lemma_tpv_3s_naive_local import MultiTaskResNet_LEMMA3S_NL
from .multi_models_lemma_tpv_3s_late_cls import MultiTaskResNet_LEMMA3S_LATE_CLS
from .multi_models_lemma_tpv_3s_plus import MultiTaskResNet_LEMMA3S_CLUSTER
from .multi_models_lemma_tpv_3s_stdiv import MultiTaskResNet_LEMMA3S_STDIV
from .multi_models_lemma_tpv_3s_txt import MultiTaskResNet_LEMMA3S_WORD
from .multi_models_lemma_tpv_3s_txt_2 import MultiTaskResNet_LEMMA3S_WORD_2
from .multi_models_lemma_tpv_3s_txt_3 import MultiTaskResNet_LEMMA3S_WORD_3
from .multi_models_lemma_tpv_3s_phrase import MultiTaskResNet_LEMMA3S_PHRASE
from .multi_models_lemma_tpv_3s_phrase_q import MultiTaskResNet_LEMMA3S_PHRASE_Q
from .multi_models_lemma_tpv_3s_2s_phrase import MultiTaskResNet_LEMMA3S_2S_PHRASE
from .multi_models_lemma_tpv_3s_2s_phrase_g import MultiTaskResNet_LEMMA3S_2S_PHRASE_G
from .multi_models_lemma_tpv_3s_2s_phrase_q import MultiTaskResNet_LEMMA3S_2S_PHRASE_Q
from .multi_models_lemma_tpv_3s_2s_phrase_cam import MultiTaskResNet_LEMMA3S_2S_PHRASE_CAM
from .multi_models_lemma_tpv_3s_2s5_phrase import MultiTaskResNet_LEMMA3S_2S5_PHRASE
from .multi_models_lemma_tpv_3s_2s_phrase_db import MultiTaskResNet_LEMMA3S_2S_PHRASE_DB
from .multi_models_lemma_tpv_3s_2s_phrase_local import MultiTaskResNet_LEMMA3S_2S_PHRASE_LC
from .multi_models_lemma_tpv_3s_2s_phrase_local_2 import MultiTaskResNet_LEMMA3S_2S_PHRASE_LC2

from .video_model_builder import ResNet, SlowFast  # noqa
# from .video_model_builder_3 import ResNet_TS_K400T, ResNet_TS_K400T_ATT
# from .video_model_builder_char_bi_base import ResNet_TS_Base
# from .video_model_builder_char_bi_base_CHR1 import ResNet_TS_Base_CHR1
# from .video_model_builder_char_bi_base_CHR2 import ResNet_TS_Base_CHR2
# from .video_model_builder_char_bi_k400 import ResNet_TS_K400_2
# from .video_model_builder_char_bi_k400_2head import ResNet_TS_K400_2Head
# from .video_model_builder_char_bi_k400_2head_1 import ResNet_TS_K400_2Head_1
# from .video_model_builder_char_bi_k400_2head_2 import ResNet_TS_K400_2Head_2
from .video_model_builder_char_bi_k400_only import ResNet_TS_K400_Only
from .video_model_builder_char_bi_k400_only_noM import ResNet_TS_K400_Only_noM
from .video_model_builder_char_bi_k400_only_CAM1 import ResNet_TS_K400_Only_CAM1
from .video_model_builder_char_bi_k400_only_CAM2 import ResNet_TS_K400_Only_CAM2
from .video_model_builder_char_bi_k400_only_CAM3 import ResNet_TS_K400_Only_CAM3
from .video_model_builder_char_bi_k400_only_CAM_CHR_2 import ResNet_TS_K400_Only_CAM_CHR
from .video_model_builder_char_bi_k400_only_CAM_CHR_3 import ResNet_TS_K400_Only_CHR_CAM3
# from .video_model_builder_char_bi_k400_only_1 import ResNet_TS_K400_Only_1
# from .video_model_builder_char_bi_k400_only_2 import ResNet_TS_K400_Only_2
# from .video_model_builder_char_bi_k400_only_CHR1 import ResNet_TS_K400_Only_CHR1
# from .video_model_builder_char_bi_k400_plus import ResNet_TS_K400_3

from .video_model_builder_charbi_con import ResNet_Con, ResNet_Con_Late, ResNet_Con_Act, ResNet_Con_2S5
from .video_model_builder_charbi_con_time import ResNet_Con_Time
from .video_model_builder_charbi_con_chr import ResNet_Con_CHR1_CLS, ResNet_Con_CHR1, ResNet_Con_CHR1_2S5
from .video_model_builder_charbi_con_chr2 import ResNet_Con_CHR2
from .video_model_builder_charbi_con_chr3 import ResNet_Con_CHR3, ResNet_Con_CHR3_2S5
from .video_model_builder_charbi_con_chr_cam import ResNet_Con_CAM, ResNet_Con_CHR_CAM
from .video_model_builder_charbi_k400_con import ResNet_Con_K400_Base
from .video_model_builder_charbi_k400_con_chr import ResNet_Con_K400_CHR
from .video_model_builder_charbi_k400_con_chr_cam import ResNet_Con_K400_CHR_CAM
from .video_model_builder_charbi_con_chr_time import ResNet_Con_CHR_CAM_Token
from .video_model_builder_charbi_con_chr_st import ResNet_Con_CHR_CAM_Token_ST
from .video_model_builder_charbi_con_chr_st2_k400 import ResNet_Con_CHR_CAM_Token_ST2_K400
from .video_model_builder_charbi_con_chr_st_k400 import ResNet_Con_CHR_CAM_Token_ST_K400
from .video_model_builder_charbi_con_chr_mae import ResNet_Con_CHR_CAM_Token_MAE

from .video_model_builder_k400_feat import ResNet_Feat
from .multi_model_k400_pos_mining import MultiTaskResNet_Feat

from .lemma_models import BiFusedModel
from .lemma_models_debug import BiFusedModel_FEAT
from .lemma_models_sf import BiFusedModel_S, BiFusedModel_SF

from .multi_model_k400_pos_mining import MultiTaskResNet_LEMMA_FEAT, MultiTaskResNet_EPIC_FEAT
